# Site Settings
title: "Fruit Fighters Docs"
author: "ISB Fruit Fighters"
navbar-links:
  Github Profile: "https://github.com/Fruit-Fighters"
  Rules: "/gameRules.md"
avatar: "/assets/img/icon.png"



# Information
social-network-links:
  email: "ISBFruitFighters@outlook.com"
  github: Fruit-fighters





# Build Settings
markdown: kramdown
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
url-pretty: "fruit-fighters.github.io"